/**
 * AM Collective — Daily Briefings Schema
 *
 * Stores the AI-generated morning briefing text for each day.
 * The Inngest morning-briefing job writes here after generating.
 * The dashboard reads here to render the morning ritual card.
 */

import {
  pgTable,
  uuid,
  date,
  text,
  boolean,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

export const dailyBriefings = pgTable(
  "daily_briefings",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    /** The calendar date this briefing covers, e.g. 2026-04-08 */
    date: date("date", { mode: "date" }).notNull(),
    /** The AI-generated briefing text (plain prose, no markdown) */
    briefingText: text("briefing_text").notNull(),
    /** True when generated by the scheduled Inngest job, false when manually triggered */
    isScheduled: boolean("is_scheduled").notNull().default(true),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { mode: "date" })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    uniqueIndex("daily_briefings_date_idx").on(table.date),
  ]
);
